### ISSUE TITLE
Missing tzdata dependency

### ISSUE THREAD

**Issue by Alurith** [ManiMozaffar/aioclock#29]
Using the example on the homepage in a new project w/ clean venv I got few validation errors about the timezone.
Example:
```shell
(cecchi_scheduler) PS D:\workspace\cecchi_scheduler> python test.py
Traceback (most recent call last):
  File "D:\workspace\cecchi_scheduler\test.py", line 25, in <module>
    @group.task(trigger=At(tz="UTC", hour=0, minute=0, second=0))
  File "D:\workspace\cecchi_scheduler\.venv\lib\site-packages\pydantic\main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for At
  Value error, Invalid timezone provided: 'No time zone found with key UTC' [type=value_error, input_value={'tz': 'UTC', 'hour': 0, 'minute': 0, 'second': 0}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
```

I have fix it installing `tzdata` maybe it should be put into the requirements.

**Comment by ManiMozaffar** [comment]
@Alurith which python version are you using?

https://github.com/ManiMozaffar/aioclock/blob/64c090440ed20ff142d7d5bf02df0bd9405fc3bd/aioclock/triggers.py#L442

this is the line that is failing. I'll investigate this, thanks for ticket!

**Comment by Alurith** [comment]
I am using Python 3.10.6 on Windows 11. I can try with other versions if you need it.

**Comment by ManiMozaffar** [comment]
I see, tzdata is actually a dependency of pydantic 2.9.0.
<img width="526" alt="Screenshot 2024-09-06 at 11 21 04" src="https://github.com/user-attachments/assets/daebacd2-787d-4c79-97e0-3ab3619ebbf2">

which is actually an optional dependency
https://github.com/pydantic/pydantic/blob/97d357f50a6e8f2a5129a2061887a9c124f7c9c3/docs/install.md?plain=1#L27

Uv (a package manager) was actually able to install the package.

<img width="508" alt="Screenshot 2024-09-06 at 11 24 36" src="https://github.com/user-attachments/assets/151cf34d-3811-4cfc-982a-64678270ea7d">

Anyway, since this is required, I'll explicitly pydantic timezone package. Already made the fix commit, will be fixed in next release
